# Public Domain (-) 2016 The GitFund Authors.
# See the GitFund UNLICENSE file for details.

HDR=`date +'[%H:%M:%S]'` ">>"

.PHONY: all clean describe watch watchloop

describe:
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "\033[31m%-10s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

all: app/model/fields.go ## Build everything
	@true

clean: ## Remove any autogenerated cruft
	@rm -f app/model/fields.go
	@rm -f genmodel

genmodel: cmd/genmodel/* app/model/model.go app/model/register.go
	@echo $(HDR) "Building genmodel"
	@go build -a github.com/tav/gitfund/cmd/genmodel

app/model/fields.go: genmodel
	@echo $(HDR) "Generating model/fields.go"
	@./genmodel > fields.go
	@mv fields.go app/model/fields.go

watch: ## Automatically run `make all` when a relevant file change is detected
	@make all
	@fswatch -0 -o \
	 -e app/model/fields.go \
	 -e genmodel \
	 -e fields.go \
	 . | xargs -0 -n1 -I{} make all

watchloop: ## Use this instead of `make watch` if you don't have fswatch installed
	@while true; do make all; sleep 1; done
