# Public Domain (-) 2016 The GitFund Authors.
# See the GitFund UNLICENSE file for details.

APPFILES := $(shell find app -name \*.go -print)
GENERATED := app/asset/files.go app/model/fields.go app/template/ego.go
HDR = `date +'[%H:%M:%S]'` ">>"

.PHONY: all clean deps describe watch watchloop

describe:
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "\033[31m%-10s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

app/.gopkgs.json: $(APPFILES) environ/gopkgs $(GENERATED)
	@echo $(HDR) "Generating gopkgs.json"
	@./environ/gopkgs app -i github.com/tav/gitfund

app/asset/files.go: environ/assets.json environ/genasset
	@echo $(HDR) "Generating asset/files.go"
	@./environ/genasset asset environ/assets.json > files.go
	@gofmt -w files.go
	@mkdir -p app/asset
	@mv files.go app/asset/files.go

app/model/fields.go: environ/genmodel
	@echo $(HDR) "Generating model/fields.go"
	@./environ/genmodel > fields.go
	@gofmt -w fields.go
	@mv fields.go app/model/fields.go

app/template/ego.go: template/*.ego
	@echo $(HDR) "Generating template/ego.go"
	@ego -o app/template/ego.go -package template
	@gofmt -w app/template/ego.go

all: $(GENERATED) ## Build everything
	@true

buildapp: app/.gopkgs.json environ/builder $(GENERATED)
	@echo $(HDR) "Building image for app"
	@./environ/builder gitfund app

checkgopkgs: environ/gopkgs $(GENERATED)
	@./environ/gopkgs -c app -i github.com/tav/gitfund

clean: ## Remove any autogenerated cruft
	@assetgen assetgen.yaml --clean
	@rm -f \
	 app/asset/files.go \
	 app/model/fields.go \
	 app/template/ego.go \
	 environ/assets.json \
	 environ/build \
	 environ/builder \
	 environ/genasset \
	 environ/genmodel \
	 environ/gopkgs \
	 environ/run \
	 fields.go \
	 files.go

deps: ## Download and build the various dependencies
	@true

environ/assets.json: assetgen.yaml
	@echo $(HDR) "Building assets.json"
	@assetgen assetgen.yaml

environ/builder: cmd/builder/builder.go
	@echo $(HDR) "Building builder"
	@go build -a -o environ/builder github.com/tav/gitfund/cmd/builder

environ/genasset: cmd/genasset/genasset.go
	@echo $(HDR) "Building genasset"
	@go build -a -o environ/genasset github.com/tav/gitfund/cmd/genasset

environ/genmodel: cmd/genmodel/genmodel.go app/model/model.go app/model/registry.go
	@echo $(HDR) "Building genmodel"
	@go build -a -o environ/genmodel github.com/tav/gitfund/cmd/genmodel

environ/gopkgs: cmd/gopkgs/gopkgs.go
	@echo $(HDR) "Building gopkgs"
	@go build -a -o environ/gopkgs github.com/tav/gitfund/cmd/gopkgs

environ/run: cmd/run/run.go
	@echo $(HDR) "Building run"
	@go build -a -o environ/run github.com/tav/gitfund/cmd/run

runapp: environ/run $(GENERATED)
	@./environ/run app -w private

rundeps:
	@memcached -d

watch: ## Automatically run `make all` when a relevant file change is detected
	@make all
	@fswatch -0 -o \
	 -e app/.gopkgs.json \
	 -e app/asset/files.go \
	 -e app/model/fields.go \
	 -e fields.go \
	 -e files.go \
	 -e environ/build \
	 -e environ/builder \
	 -e environ/genasset \
	 -e environ/genmodel \
	 -e environ/gopkgs \
	 -e environ/run \
	 . | xargs -0 -n1 -I{} make all

watchloop: ## Use this instead of `make watch` if you don't have fswatch installed
	@while true; do make all; sleep 1; done
