#! /usr/bin/env python3

# Public Domain (-) 2017 The GitFund Authors.
# See the GitFund UNLICENSE file for details.

"""Script to find unused CSS classes."""

import re
import sys

from os import listdir
from os.path import join

if len(sys.argv) != 3:
    print("Usage: check-css path/to/style.coffee path/to/templates/directory")
    sys.exit(1)

css_path, templates_dir = sys.argv[1:]

classes = set()
with open(css_path, 'r') as css_file:
    for line in css_file:
        line = line.strip()
        if not line.endswith(':'):
            continue
        if '@' in line:
            continue
        if '#' in line:
            continue
        if '.' not in line:
            continue
        line = line[1:-2]
        for selector in line.split(','):
            for cls in selector.strip().split('.', 1)[1].split('.'):
                classes.add(cls)

seen = set()
for filename in listdir(templates_dir):
    if not filename.endswith('.mako'):
        continue
    with open(join(templates_dir, filename), 'r') as tmpl:
        tmpl = tmpl.read()
        for match in re.findall('class="([^"]*[^"]*)"', tmpl):
            if '$' in match:
                left, right = match.split('${', 1)
                for submatch in re.findall("'([^']*[^']*)'", match):
                    for cls in filter(None, submatch.split()):
                        seen.add(cls)
                for cls in filter(None, left.split()):
                    seen.add(cls)
            else:
                for cls in filter(None, match.split()):
                    seen.add(cls)

for cls in sorted(classes):
    if cls not in seen:
        print("!! Potentially unused: .%s\n" % cls)
